class Food {
  final String name;
  final String portionDescription;
  final int gramWeight;
  final double gramProtein;
  final double gramFat;
  final double gramCarbohydrate;
  final double kcalEnergy;
  final int fdcId;

  const Food(
      {required this.name,
      required this.portionDescription,
      required this.gramWeight,
      required this.gramProtein,
      required this.gramFat,
      required this.gramCarbohydrate,
      required this.kcalEnergy,
      required this.fdcId});
}

const allFoods = [
  Food(
      name: "Milk, human",
      portionDescription: "1 cup",
      gramWeight: 246,
      gramProtein: 1.03,
      gramFat: 4.38,
      gramCarbohydrate: 6.89,
      kcalEnergy: 70.0,
      fdcId: 1097510),
  Food(
      name: "Milk, NFS",
      portionDescription: "1 cup",
      gramWeight: 244,
      gramProtein: 3.34,
      gramFat: 1.99,
      gramCarbohydrate: 4.87,
      kcalEnergy: 51.0,
      fdcId: 1097511),
  Food(
      name: "Milk, whole",
      portionDescription: "1 cup",
      gramWeight: 244,
      gramProtein: 3.28,
      gramFat: 3.2,
      gramCarbohydrate: 4.67,
      kcalEnergy: 60.0,
      fdcId: 1097512),
  Food(
      name: "Milk, low sodium, whole",
      portionDescription: "1 cup",
      gramWeight: 244,
      gramProtein: 3.1,
      gramFat: 3.46,
      gramCarbohydrate: 4.46,
      kcalEnergy: 61.0,
      fdcId: 1097513),
  Food(
      name: "Milk, calcium fortified, whole",
      portionDescription: "1 cup",
      gramWeight: 244,
      gramProtein: 3.28,
      gramFat: 3.2,
      gramCarbohydrate: 4.67,
      kcalEnergy: 60.0,
      fdcId: 1097514),
  Food(
      name: "Milk, calcium fortified, low fat (1%)",
      portionDescription: "1 cup",
      gramWeight: 244,
      gramProtein: 3.38,
      gramFat: 0.95,
      gramCarbohydrate: 5.19,
      kcalEnergy: 43.0,
      fdcId: 1097515),
  Food(
      name: "Milk, calcium fortified, fat free (skim)",
      portionDescription: "1 cup",
      gramWeight: 244,
      gramProtein: 3.4,
      gramFat: 0.18,
      gramCarbohydrate: 4.85,
      kcalEnergy: 35.0,
      fdcId: 1097516),
  Food(
      name: "Milk, reduced fat (2%)",
      portionDescription: "1 cup",
      gramWeight: 244,
      gramProtein: 3.35,
      gramFat: 1.9,
      gramCarbohydrate: 4.91,
      kcalEnergy: 50.0,
      fdcId: 1097517),
  Food(
      name: "Milk, acidophilus, low fat (1%)",
      portionDescription: "1 cup",
      gramWeight: 244,
      gramProtein: 3.38,
      gramFat: 0.95,
      gramCarbohydrate: 5.19,
      kcalEnergy: 43.0,
      fdcId: 1097518),
  Food(
      name: "Milk, acidophilus, reduced fat (2%)",
      portionDescription: "1 cup",
      gramWeight: 244,
      gramProtein: 3.35,
      gramFat: 1.9,
      gramCarbohydrate: 4.91,
      kcalEnergy: 50.0,
      fdcId: 1097519),
  Food(
      name: "Milk, low fat (1%)",
      portionDescription: "1 cup",
      gramWeight: 244,
      gramProtein: 3.38,
      gramFat: 0.95,
      gramCarbohydrate: 5.19,
      kcalEnergy: 43.0,
      fdcId: 1097520),
  Food(
      name: "Milk, fat free (skim)",
      portionDescription: "1 cup",
      gramWeight: 244,
      gramProtein: 3.43,
      gramFat: 0.08,
      gramCarbohydrate: 4.89,
      kcalEnergy: 34.0,
      fdcId: 1097521),
  Food(
      name: "Milk, lactose free, low fat (1%)",
      portionDescription: "1 cup",
      gramWeight: 244,
      gramProtein: 3.38,
      gramFat: 0.95,
      gramCarbohydrate: 5.19,
      kcalEnergy: 43.0,
      fdcId: 1097522),
  Food(
      name: "Milk, lactose free, fat free (skim)",
      portionDescription: "1 cup",
      gramWeight: 244,
      gramProtein: 3.43,
      gramFat: 0.08,
      gramCarbohydrate: 4.89,
      kcalEnergy: 34.0,
      fdcId: 1097523),
  Food(
      name: "Milk, lactose free, reduced fat (2%)",
      portionDescription: "1 cup",
      gramWeight: 244,
      gramProtein: 3.35,
      gramFat: 1.9,
      gramCarbohydrate: 4.91,
      kcalEnergy: 50.0,
      fdcId: 1097524),
  Food(
      name: "Milk, lactose free, whole",
      portionDescription: "1 cup",
      gramWeight: 244,
      gramProtein: 3.28,
      gramFat: 3.2,
      gramCarbohydrate: 4.67,
      kcalEnergy: 60.0,
      fdcId: 1097525),
  Food(
      name: "Buttermilk, fat free (skim)",
      portionDescription: "1 cup",
      gramWeight: 244,
      gramProtein: 3.31,
      gramFat: 1.07,
      gramCarbohydrate: 4.79,
      kcalEnergy: 40.0,
      fdcId: 1097526),
  Food(
      name: "Buttermilk, low fat (1%)",
      portionDescription: "1 cup",
      gramWeight: 244,
      gramProtein: 3.31,
      gramFat: 1.07,
      gramCarbohydrate: 4.79,
      kcalEnergy: 40.0,
      fdcId: 1097527),
  Food(
      name: "Buttermilk, reduced fat (2%)",
      portionDescription: "1 cup",
      gramWeight: 244,
      gramProtein: 4.1,
      gramFat: 2.0,
      gramCarbohydrate: 5.3,
      kcalEnergy: 56.0,
      fdcId: 1097528),
  Food(
      name: "Buttermilk, whole",
      portionDescription: "1 cup",
      gramWeight: 244,
      gramProtein: 3.21,
      gramFat: 3.31,
      gramCarbohydrate: 4.88,
      kcalEnergy: 62.0,
      fdcId: 1097529),
  Food(
      name: "Kefir, NS as to fat content",
      portionDescription: "1 cup",
      gramWeight: 244,
      gramProtein: 3.59,
      gramFat: 0.96,
      gramCarbohydrate: 7.48,
      kcalEnergy: 52.0,
      fdcId: 1097530),
  Food(
      name: "Goat's milk, whole",
      portionDescription: "1 cup",
      gramWeight: 244,
      gramProtein: 3.56,
      gramFat: 4.14,
      gramCarbohydrate: 4.45,
      kcalEnergy: 69.0,
      fdcId: 1097531),
];
